### PR TITLE
[C] [C++] General fixes/improvements

### LINKED ISSUE #28: [C++] RSDK::Matrix multiplication operator breaks build with Linux/gcc-c++ on STL >= 23
Mentioning Linux/gcc because this seemed to work just fine on Windows/MSVC last time I checked. I could be wrong though
Fedora - gcc version 15.2.1 20250808 (Red Hat 15.2.1-1) (GCC)

```c++
friend inline Matrix operator*(Matrix &lhs, Matrix &rhs)
{
    Matrix dest;
    Matrix::Multiply(&dest, &lhs, &rhs);
    return dest;
}
```

```
error: cannot bind non-const lvalue reference of type ‘RSDK::Matrix&’ to an rvalue of type ‘RSDK::Matrix’
```

```cmake
cmake_minimum_required(VERSION 3.20)
project(RSSav2)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if (CMAKE_COMPILER_IS_GNUCC)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpermissive")
endif ()

set(GAME_NAME "Source" CACHE STRING "The game directory to look into")
set(GAME_OUTPUT_NAME "Game" CACHE STRING "The name of the built library")

add_compile_definitions(GAME_CUSTOMLINKLOGIC)

option(WITH_RSDK "Whether or not to build with RSDKv5. Defaults to true" OFF) #ON)
option(GAME_STATIC "Whether or not to build the game as a static library." $<BOOL:$<IF:WITH_RSDK,ON,OFF>>)

if (NOT DEFINED GAME_STATIC)
    if (WIN32)
        set(GAME_STATIC OFF)
    elseif (UNIX)
        set(GAME_STATIC OFF)
    else ()
        set(GAME_STATIC ON)
    endif ()
endif ()

option(ORIGINS_FIRST_RELEASE "" OFF)
if (ORIGINS_FIRST_RELEASE)
    set(ORIGINS_PREPLUS ON)
else ()
    option(ORIGINS_PREPLUS "" OFF)
endif ()

if (NOT ORIGINS_PREPLUS)
    set(GAME_VERSION 6 CACHE STRING "The game version to use. Defaults to 6 == Last Steam release")
else ()
    set(GAME_VERSION 3 CACHE STRING "The game version to use. Defaults to 3 == Last pre-plus release")
endif ()

find_path(GAMEAPI
    NAMES
    C
    CPP

    HINTS
    ${CMAKE_CURRENT_SOURCE_DIR}/dependencies
    ${CMAKE_SOURCE_DIR}/dependencies

    PATHS
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/..

    PATH_SUFFIXES
    GameAPI
    RSDKv5-GameAPI

    NO_DEFAULT_PATH
    NO_CMAKE_FIND_ROOT_PATH
)

if (GAMEAPI)
    message(STATUS "Found GameAPI for ${GAME_NAME}: ${GAMEAPI}")
else ()
    message(FATAL_ERROR "GameAPI not found for ${GAME_NAME}. Clone it in the dependencies.")
endif ()

option(GAME_INCLUDE_EDITOR "Whether or not to include editor functions. Defaults to true" ON)
option(GAME_INCREMENTAL_BUILD "Whether or not to build all objects separately (for quicker dev-->build iterations). Defaults to false." OFF)

if (GAME_INCREMENTAL_BUILD)
    include(${GAME_NAME}/Objects/Objects.cmake)
    set(GAME_SOURCES
        ${GAMEAPI}/CPP/GameAPI/Game.cpp
        ${GAME_NAME}/Game.cpp
        ${GENERATED_SOURCES}
    )
else ()
    set(GAME_SOURCES
        ${GAMEAPI}/CPP/GameAPI/Game.cpp
        ${GAME_NAME}/RSSav2.cxx
        ${GAME_NAME}/Objects/All.cpp
    )
endif ()

if (GAME_STATIC)
    add_library(${GAME_NAME} STATIC ${GAME_SOURCES})
else ()
    add_library(${GAME_NAME} SHARED ${GAME_SOURCES})
endif ()

target_include_directories(${GAME_NAME} PRIVATE
    ${GAMEAPI}/CPP/
    ${GAME_NAME}/
    ${GAME_NAME}/Objects/
)

if (WIN32)
    target_compile_definitions(${GAME_NAME} PRIVATE _CRT_SECURE_NO_WARNINGS)
endif ()

if (APPLE)
    set_target_properties(${GAME_NAME} PROPERTIES PREFIX "")
endif ()

set_target_properties(${GAME_NAME} PROPERTIES OUTPUT_NAME ${GAME_OUTPUT_NAME})

if (WITH_RSDK)
    set(RSDK_PATH dependencies/RSDKv5 CACHE STRING "The path to look for RSDKv5 if using WITH_RSDK.")

    add_subdirectory(${RSDK_PATH})

    if (GAME_STATIC)
        target_include_directories(RetroEngine PRIVATE ${GAME_NAME}/)
        target_link_libraries(RetroEngine ${GAME_NAME})
    endif ()
else ()
    set(RETRO_REVISION 3 CACHE STRING "What revision to compile for. Defaults to v5U = 3")

    option(RETRO_MOD_LOADER "Enables or disables the mod loader." ON)
    set(RETRO_MOD_LOADER_VER 2 CACHE STRING "Sets the mod loader version. Defaults to latest")

    target_compile_definitions(${GAME_NAME} PRIVATE
        RETRO_REVISION=${RETRO_REVISION}
        RETRO_USE_MOD_LOADER=$<BOOL:${RETRO_MOD_LOADER}>
        RETRO_MOD_LOADER_VER=${RETRO_MOD_LOADER_VER}
        GAME_INCLUDE_EDITOR=$<BOOL:${GAME_INCLUDE_EDITOR}>
        ORIGINS_PREPLUS=$<BOOL:${ORIGINS_PREPLUS}>
        ORIGINS_FIRST_RELEASE=$<BOOL:${ORIGINS_FIRST_RELEASE}>
        GAME_VERSION=${GAME_VERSION}
    )
endif ()

if (MSVC)
    target_link_options(${GAME_NAME} PRIVATE /OPT:NOICF)
endif ()
```

### LINKED ISSUE #30: [C++] Unnecessary/Incorrect `foreach_break` and `foreach_return`
In the C API, foreach loops are handled through macros, where the `foreach_break` and `foreach_return` macros serve a purpose as they need to call `RSDK.BreakForeachLoop()` before exiting the loop. In the C++ API, however, foreach loops are handled by first constructing an std::list of all entities in GameObject::GetEntities, and _then_ the loop code is ran after the entire entity list has been formed. Despite this, however, the C++ GameAPI bindings still include the `foreach_break` and `foreach_return` macros, despite simply `break` and `return` being all that's needed. Beyond being unnecessary, these macros incorrectly include calls to `RSDK::RSDKTable->BreakForeachLoop()`, which decrement the foreach stack pointer despite the GetActive/AllEntities loop already being completed.

### PR DESCRIPTION
**Pull request by Jdaslepre**
Fixes #28, Fixes #30

### CODE REVIEW

File: CPP/GameAPI/RSDKv5/Debugging/Dev.hpp [hunk 1]
```diff
@@ -34,9 +34,6 @@ typedef enum {
     PRINT_POPUP,
     PRINT_ERROR,
     PRINT_FATAL,
-#if RETRO_REV0U
-    PRINT_SCRIPTERR,
-#endif
```
Comment (Mefiresu) [inline CPP/GameAPI/RSDKv5/Debugging/Dev.hpp:39]: Keep this for consistency with the engine code:

Image

File: README.md [hunk 2]
```diff
@@ -1,4 +1,30 @@
-# GameAPI
-Sonic Mania modding API
+## RSDKv5-GameAPI
+An API bindings library, used for modding/developing projects based on the [Retro Engine v5](https://RSDKModding.com/RSDKv5) and its [decompilation](https://github.com/RSDKModding/RSDKv5-Decompilation).
```
Comment (Mefiresu) [inline README.md]:
```suggestion
An API bindings library, used for modding/developing projects based on the [Retro Engine v5](https://rsdkmodding.com/RSDKv5) and its [decompilation](https://github.com/RSDKModding/RSDKv5-Decompilation).
```

File: C/GameAPI/GameVariables.h [hunk 3]
```diff
@@ -554,110 +611,121 @@ typedef struct {
...
     int32 atlCameraBoundsT[PLAYER_COUNT];
     int32 atlCameraBoundsB[PLAYER_COUNT];
     Vector2 atlCameraPos[PLAYER_COUNT];
     Vector2 atlOffset;
-    int32 unknownValues[4];
-    int32 unknownValues2[4];
-    int32 field_447CA4;
+    uint8 atlScratchRAM[0x20];
+    int32 atlTimer;
     bool32 tileCollisionMode;
```
Comment (Mefiresu) [inline C/GameAPI/GameVariables.h]: In the `GameVariables.cpp` file, this has been changed to an `int32`, need to match to whatever is supposed to be the right type for consistency.

File: CPP/GameAPI/RSDKv5/Debugging/Dev.hpp [hunk 4]
```diff
@@ -56,6 +53,7 @@ inline void Print(PrintModes severity, const char *message, ...)
     vsprintf_s(buffer, message, args);
     RSDKTable->PrintLog(severity, buffer);
 };
+inline void PrintText(PrintModes severity, const char *message) { RSDKTable->PrintText(severity, message); };
```
Comment (Mefiresu) [inline CPP/GameAPI/RSDKv5/Debugging/Dev.hpp]:
```suggestion
inline void PrintText(PrintModes severity, const char *message) { RSDKTable->PrintText(severity, message); }
```

File: CPP/GameAPI/GameVariables.hpp [hunk 5]
```diff
@@ -360,16 +413,17 @@ enum NotifyCallbackIDs {
     NOTIFY_STATS_SAVE_FUTURE   = 0xA4,
     NOTIFY_STATS_CHARA_ACTION2 = 0xA5,
 
-    NOTIFY_1000                = 1000,
```
Comment (Mefiresu) [inline CPP/GameAPI/GameVariables.hpp:363]: Not even in older v5U versions?

File: CPP/GameAPI/RSDKv5/Math/Matrix.hpp [hunk 6]
```diff
@@ -6,33 +6,37 @@ namespace RSDK
...
-        Matrix::Multiply(this, this, &other);
+        Matrix temporary = { *this };
+        Matrix::Multiply(this, &temporary, const_cast<Matrix *>(&other));
         return *this;
     }
 
     friend inline Matrix operator*(Matrix &lhs, Matrix &rhs)
     {
-        Matrix dest;
+        Matrix dest = {};
```
Comment (Mefiresu) [inline CPP/GameAPI/RSDKv5/Math/Matrix.hpp]: I don't think this zero init is needed, a multiply will already replace all elements in the Matrix.

File: CPP/GameAPI/RSDKv5/Game/Object.hpp [hunk 7]
```diff
@@ -265,77 +265,43 @@ struct GameObject {
...
-        if (type == FOR_ALL_ENTITIES) {
-            while (RSDKTable->GetAllEntities(group, (void **)&entity)) list.push_back(entity);
-        }
-        else if (type == FOR_ACTIVE_ENTITIES) {
-            while (RSDKTable->GetActiveEntities(group, (void **)&entity)) list.push_back(entity);
-        }
+    template <typename T> struct EntityIterator {
+        T *entity;
+        uint16 group;
+        int32 type;
```
Comment (Mefiresu) [inline CPP/GameAPI/RSDKv5/Game/Object.hpp]: Any reason not to use ForeachGroups/ForeachTypes anymore for those? Could reuse them and specify their size on the enum directly if you're worried about matching type?
